---
# Build up the ansible container for our demo
services:

  ansible-controller:
    image: nirgeier/ansible-controller
    container_name: ansible-controller
    environment:
       ANSIBLE_CONFIG: /labs-scripts/ansible.cfg
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${ROOT_FOLDER}/runtime/.ssh:/root/.ssh
      - ${ROOT_FOLDER}/runtime/labs-scripts:/labs-scripts

  linux-server-1:
    image: nirgeier/linux-server-1
    container_name: linux-server-1
    hostname: linux-server-1
    ports:
      - "0.0.0.0:3001:22"
      - "0.0.0.0:5001:5000"
      - "0.0.0.0:8081:8080"
    environment:
      hostname: linux-server-1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  linux-server-2:
    image: nirgeier/linux-server-2
    container_name: linux-server-2
    hostname: linux-server-2
    ports:
      - "0.0.0.0:3002:22"
      - "0.0.0.0:5002:5000"
      - "0.0.0.0:8082:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      hostname: linux-server

  linux-server-3:
    image: nirgeier/linux-server-3
    container_name: linux-server-3
    hostname: linux-server-3
    ports:
      - "0.0.0.0:3003:22"
      - "0.0.0.0:5003:5000"
      - "0.0.0.0:8083:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      hostname: linux-server-3
