kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  disableDefaultCNI: true # Disable default kindnet so we can install Calico
  podSubnet: 192.168.0.0/16 # Calico default pod CIDR
nodes:
  - role: control-plane
  - role: worker
  - role: worker
