---
# List of hosts
- name: Sample Playbook
  hosts: localhost

  ###
  ### In this sample we display several solutions
  ###
  ### We combine few commands like: `shell`, `debug`, `command` and more
  ###
  # List of tasks
  tasks:
    # Using shell it will work, but no out put will be displayed out
    # We will need to use register to display output
    - name: Execute 'uname -a'
      shell: uname -a
      register: task_output
    # Using register we can now display the output contents
    # We must use `.stdout` to display the output itself
    - name: Print 'uname -a' output
      debug:
        msg: "{{ task_output.stdout }}"

    # In class Hands-on task
    - name: Execute 'id'
      command: id
      register: id_output

    - name: Print 'id' output
      debug:
        msg: "{{ id_output.stdout }}"
